### ISSUE TITLE
Вынести блок faq на странице privacy-policy в section

### ISSUE THREAD

**Issue by sylvan008** [VadimCpp/vadimcpp.ru#103]
1. Тегу `body` добавить класс `page`
2. Необходимо вынести блок FAQ в `section` и добавить класс `faq`.
  Должна получиться структура:
  ```
  <section class="faq page_faq">
    <h2 class="faq_header">
    <dl class="faq_list">
      <dt class="faq_question">
      <dd class="faq_answer">
  ```
3. Удалить все "технические" классы бутстрап для отступов в заголовке и списке. Удалить с заголовка класс `h4`.
4. Перенести в класс `faq_header` стили заголовка `h4` и центрирование текста и нижний отступ (визуальная часть не должна измениться).
5. В списке удалить тег `b`, т.к. у него нет семантического значения.
6. Добавить стили отступов в классы `faq_question`, `faq_answer`.
7. Добавить стилизацию текста (жирность) в класс `faq_question`.
8. Добавить верхний отступ в класс `page_faq`.

**Comment by VadimCpp** [comment]
По всем вопросам консультироваться у Олега:
https://t.me/Oleg_Sylvan008

**Comment by VadimCpp** [comment]
Спасибо @sylvan008 @Bylinskiy задачу закрыл
